add np.stack
Quansight-Labs/udiff pull request #31
Opened 2020-08-06 14:58 UTC by sangyx

I have added the diff function of `np.stack`. 

When we extend the code to higher-order derivatives, the situation becomes a bit more complicated. There are some places to improve:

* In some derivative functions, the program may enter an infinite loop. For example, `np.sum` is used when registering the gradient of `np.sum`. I plan to add depth attributes to `DiffArray` or `to()` to control the order of gradients.
* The function registered in nograd_functions will register the gradient when it is called in the form of `ufunc.__call__`.
* Consider a cleaner way to control whether the calculation should derive.

Do you have any idea about the above questions?

2020-08-06 16:01 UTC, hameerabbasi commented
Ah, yes. I remember running into this when I was initially working with `udiff`. Basically, in your approach, it would work as follows:

- The `DiffArray.to` method should only compute the diff with respect to what's passed in, not anything else.
- `DiffArray.backward` should only compute the calculation graph, but only for "the current level". The next level should remain "unevaluated" or in the form of a graph until you actually call `DiffArray.diff[some_name].backward`.

2020-08-08 16:23 UTC, sangyx commented
I have fixed the problem, we have to put all the calculations that need to register gradients in each diff function in `lambda g` (or `vjp`), so as to avoid infinite loops.

The errors of `<uarray multimethod '__instancecheck__'>` in ci seem to be related to `uarray`.

2020-08-08 17:02 UTC, hameerabbasi commented
I'll fix those up. Don't worry about them for now.

2020-08-13 13:07 UTC, hameerabbasi commented
@peterbell10 I can reproduce the segfault in CI. Is it possible for you to investigate? I was also getting a bunch of "returned NULL without setting an error" on `determine_backend`.

2020-08-18 08:41 UTC, hameerabbasi commented
@sangyx Passing the torch back to you. 😄 The segfaults  should be resolved now.

2020-08-18 15:07 UTC, sangyx commented
Thanks!

2020-08-19 07:11 UTC, sangyx commented
@hameerabbasi Hi, I want to add `<uarray multimethod '__instancecheck__'>` to `raw_functions`. But I don't know how to refer it. How can I find it by code like `np.ndim`?

2020-08-19 07:16 UTC, hameerabbasi commented
> Hi, I want to add `<uarray multimethod '__instancecheck__'>` to `raw_functions`. But I don't know how to refer it. How can I find it by code like `np.ndim`?

You can probably do something like `unumpy.ClassOverrideMeta.__instancecheck__`.

2020-08-19 08:13 UTC, sangyx commented
@hameerabbasi Could you help me to check whether the `NoGradBackend` is correct?

2020-08-19 08:30 UTC, hameerabbasi commented on src/udiff/_vjp_diffs.py
> +        )
Can you write shape manipulations in loops, i.e. completely without NumPy?

2020-08-20 09:23 UTC, hameerabbasi requested changes
Thanks, @sangyx. A few minor comments and then it should be good to go.

2020-08-20 09:23 UTC, hameerabbasi commented on src/udiff/_uarray_plug.py
> +class NoGradBackend:
You can remove `NoGradBackend` and instead use the following directly:

```python
with ua.set_backend(self._inner, coerce=True):
    out = func(*args, **kwargs)
```

2020-08-20 09:23 UTC, hameerabbasi commented on README.md
> +with ua.set_backend(numpy_backend, coerce=True), ua.set_backend(udiff, coerce=True):
This line needs updating.
```suggestion
with ua.set_backend(udiff.DiffArrayBackend(numpy_backend), coerce=True):
```

2020-08-20 09:23 UTC, hameerabbasi commented on README.md
> +with ua.set_backend(numpy_backend, coerce=True), ua.set_backend(udiff, coerce=True):
As do the notebooks.

2020-08-20 09:23 UTC, hameerabbasi commented on src/tests/test_jacobian.py
> +#     )
Remove these lines.

2020-08-20 16:03 UTC, merged

2020-08-20 16:24 UTC, hameerabbasi commented
Thanks @sangyx!